spring.application.name=PP-3_3_1_springBootApp
# MySQL properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/springBootDB
spring.datasource.username=root
spring.datasource.password=123

# Hibernate properties
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=create

spring.jpa.open-in-view=false
